language: node_js
node_js: node
branches:
  only: master
install:
- npm install
before_script:
- echo -e "Host $HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: npm run compile
before_deploy:
- cd dist
deploy:
  skip_cleanup: true
  provider: npm
  email: asmodeusxi@gmail.com
  on:
    branch: master
  api_key:
    secure: gTKCANTaxHelrf2lIT5Fd+hUsmtOn1/gVwh0fsmZBa7utIIrtRibSv0h4X2LbBTCY6iFT17hFx6SwkAtpWomvnG+xPhGeEE8vBeP6pKwSLkbecT/jygMfouQXKafd5WvbQKrpITGIcYunNMJGY9i9JdPE46hw6jE1bawfkeXS0xVAhUK6fJFZmkZqhXRsEVbsOPp7h11pq/iQB3ec4N2UKGwfBPZsT1cFLXwmrzisVee4BGDDu12TvPlpzRXAOSL/ewOsVOxa+650Yb5pjo6CgsMWvtX/GSLe3OkxNLzN5Pbq3aJpa7d7he8ghFOWK7uzOFhuJll20JNVm5FwXPQK7oJdbC5NeY+JnjfaaqkWOLK9q1l/DrCrDw0X9to6smSrSBAcagP7REQ96OvoJ6ZPNCE60d4UxuYKUObD9AxgAccdeHshBVjBO2axpPx2gm6nDPVNtSP85j22yG70SkhIG7W0j2sJ8RKpCUdapl4EGL8T0CXfjJyfjCKH2jLMVmrP6ZzZVXI+MMDrIt7kJ/jVdiBz19+IRLlTjowtlTr3r8x4pfSnKwV+PevH/7doHXJXeZu5YOmtgaladHvwAO9XV91CDoYYAtuugRI6y16mTV1LTvx9l4qaNVEKyq0DHj1srOeW+hZjur4OkSJpor19swRzlHyXE44eWukzk4pIqg=
