language: node_js
node_js: node
branches:
  only: master
install:
- npm install
before_script:
- echo -e "Host $HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: asmodeusxi@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
